import { ArrowRight, BookOpen, Database, FileCheck2, Layers3, Search } from "lucide-react";
import Link from "next/link";

import { PipelineDiagram } from "@/components/pipeline-diagram";
import { CoverageCard, DataQualityPanel, DemoBanner, MetricCard, SectionHeading } from "@/components/research-ui";
import { Button } from "@/components/ui/button";
import { getArticles, getDataProfile, getMetrics } from "@/lib/data-loader";
import { formatNumber, formatPercent } from "@/lib/utils";

const questions = ["Which food products appear most frequently in reported incidents?", "Which adulterants and safety issues are reported?", "Where are incidents concentrated?", "What enforcement actions are taken?", "Where do news reports align with or diverge from FSSAI surveys?", "Which issues fall outside the parameters examined by official surveys?"];

export default function OverviewPage() {
  const articles = getArticles();
  const metrics = getMetrics(articles);
  const profile = getDataProfile(articles);
  const oil = articles.filter((article) => article.food_keyword === "Edible Oil");
  const ghee = articles.filter((article) => article.food_keyword === "Ghee");
  const oilReviewed = oil.filter((article) => article.human_label !== "pending").length;
  const gheeReviewed = ghee.filter((article) => article.human_label !== "pending").length;
  const relevantShare = metrics.reviewed ? metrics.relevant / metrics.reviewed : 0;

  return <>{profile.isDemo && <DemoBanner />}
    <section className="border-b border-[var(--line)] bg-[var(--white)]"><div className="section-shell grid min-h-[640px] gap-12 py-16 lg:grid-cols-[1.35fr_.65fr] lg:items-end lg:py-24"><div><p className="eyebrow rule-label">Food Computing Lab, Ashoka University</p><h1 className="font-editorial mt-8 max-w-5xl text-5xl leading-[1.02] text-[var(--maroon-dark)] sm:text-6xl lg:text-7xl">Indian Food Safety Incident Observatory</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-[var(--muted)]">Tracking food adulteration and food-safety incidents through news evidence, FSSAI reports and an Indian food ontology.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild><Link href="/incidents">Explore incidents <ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="secondary"><Link href="/methodology">View methodology</Link></Button></div></div><aside className="border-l-2 border-[var(--saffron)] pl-6"><p className="text-sm font-semibold text-[var(--maroon)]">Two evidence layers</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">News articles provide recent incident-level evidence. FSSAI surveys provide official structured and laboratory-tested baselines. The Observatory keeps their scope and evidentiary status distinct.</p></aside></div></section>
    <section className="section-shell py-14"><div className="grid gap-px bg-[var(--line)] sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Corpus records" value={metrics.total} note={`${formatNumber(metrics.reviewed)} human reviewed`} icon={Database} /><MetricCard label="Relevant articles" value={metrics.relevant} note="Human-reviewed labels only" icon={FileCheck2} /><MetricCard label="Irrelevant articles" value={metrics.irrelevant} note="Retained as an audit trail" icon={Search} /><MetricCard label="Food categories covered" value={metrics.categories} note="Edible Oil and Ghee" icon={Layers3} /></div></section>
    <section className="border-y border-[var(--line)] bg-[var(--paper-deep)]"><div className="section-shell py-16"><SectionHeading eyebrow="Current coverage" title="A staged research corpus" description="Coverage reflects files currently loaded into the website. Human labels and classifier outputs are stored separately." /><div className="mt-9 grid gap-6 md:grid-cols-2"><CoverageCard title="Edible Oil" status="Human relevance classification is complete for the current master corpus. Event extraction and ontology mapping are underway." progress={oil.length ? oilReviewed / oil.length : 0} stats={`${formatNumber(oilReviewed)} of ${formatNumber(oil.length)} records human reviewed`} tone="complete" /><CoverageCard title="Ghee" status="Manual labelling is in progress. Existing edible-oil models have been tested as an unchanged transfer baseline; a ghee-specific classifier is not yet final." progress={ghee.length ? gheeReviewed / ghee.length : 0} stats={`${formatNumber(gheeReviewed)} of ${formatNumber(ghee.length)} records human reviewed`} tone="progress" /></div></div></section>
    <section className="section-shell py-20"><SectionHeading eyebrow="Research workflow" title="How the Observatory works" description="Completed, active and planned stages are shown directly from the current project status." /><div className="mt-10"><PipelineDiagram /></div></section>
    <section className="bg-[var(--maroon-dark)] text-white"><div className="section-shell grid gap-12 py-20 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow !text-[#e9bd7b]">Research questions</p><h2 className="font-editorial mt-4 text-4xl">What can incident evidence reveal?</h2><p className="mt-5 leading-7 text-white/65">The interface is designed for transparent exploration, not causal inference or independent verification of news claims.</p></div><ol className="grid gap-px bg-white/15 sm:grid-cols-2">{questions.map((question, index) => <li key={question} className="min-h-36 bg-[var(--maroon-dark)] p-6"><span className="text-xs font-semibold text-[#e9bd7b]">{String(index + 1).padStart(2, "0")}</span><p className="mt-4 leading-6 text-white/85">{question}</p></li>)}</ol></div></section>
    <section className="section-shell py-20"><SectionHeading eyebrow="Latest findings" title="What the loaded data can support today" description="These are data-completion observations calculated from the current export, not claims about population-level food-safety trends." /><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_1fr_.8fr]"><article className="border-t-2 border-[var(--saffron)] py-6"><p className="font-editorial text-5xl text-[var(--maroon-dark)]">{formatPercent(relevantShare, 1)}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">of the {formatNumber(metrics.reviewed)} human-reviewed records are labelled relevant to the project criteria.</p></article><article className="border-t-2 border-[var(--saffron)] py-6"><p className="font-editorial text-5xl text-[var(--maroon-dark)]">{formatNumber(metrics.classifierScored)}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">records have trained-classifier predictions. Future large-model validation fields remain unpopulated.</p></article><DataQualityPanel total={metrics.total} reviewed={metrics.reviewed} scored={metrics.classifierScored} extraction={metrics.extractionComplete} /></div><div className="mt-10 flex justify-end"><Button asChild variant="secondary"><Link href="/incidents">Search the repository <ArrowRight className="h-4 w-4" /></Link></Button></div></section>
    <section className="border-t border-[var(--line)] bg-[var(--white)]"><div className="section-shell flex flex-col gap-6 py-12 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><BookOpen className="mt-1 h-6 w-6 text-[var(--saffron)]" /><div><h2 className="font-editorial text-2xl">Read the evidence with its limitations</h2><p className="mt-1 text-sm text-[var(--muted)]">Review discovery, labelling, validation and model-evaluation decisions.</p></div></div><Button asChild variant="secondary"><Link href="/methodology">Methodology</Link></Button></div></section>
  </>;
}
