import { BookOpen, Building2, Database, Network } from "lucide-react";
import type { Metadata } from "next";
import { PageIntro, SectionHeading } from "@/components/research-ui";

export const metadata: Metadata = { title: "About" };
const roles = [
  [Database, "News evidence", "Provides recent, incident-level reports and an auditable record of relevance decisions. News coverage is incomplete and claims require careful interpretation."],
  [Building2, "FSSAI evidence", "Provides official structured and laboratory-tested survey baselines with explicit parameters, sampling designs and scope limitations."],
  [Network, "Indian food ontology", "Will provide stable concepts and relationships for food products, issues, evidence and regulatory comparison once validated ontology data are supplied."],
] as const;

export default function AboutPage() { return <><PageIntro eyebrow="About" title="A research infrastructure for Indian food-safety evidence" description="The Observatory is being developed in the Food Computing context at Ashoka University to make incident-level news evidence searchable, inspectable and comparable with official baselines." aside={<p>The interface is a research prototype. It does not provide consumer alerts, legal determinations or independent verification of publisher claims.</p>} /><div className="section-shell py-16"><section><SectionHeading eyebrow="Project objective" title="Connect evidence without collapsing its differences" description="The project builds a transparent chain from article discovery to human review, classification, event validation, entity extraction, ontology mapping and FSSAI comparison." /><div className="mt-9 grid gap-6 md:grid-cols-3">{roles.map(([Icon, title, description]) => <article className="border-t-2 border-[var(--saffron)] py-6" key={title}><Icon className="h-6 w-6 text-[var(--maroon)]" /><h2 className="font-editorial mt-5 text-2xl text-[var(--maroon-dark)]">{title}</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{description}</p></article>)}</div></section><section className="mt-20 border-y border-[var(--line)] bg-[var(--white)] px-6 py-10 md:px-10"><div className="grid gap-8 md:grid-cols-[.7fr_1.3fr]"><div><BookOpen className="h-6 w-6 text-[var(--saffron)]" /><h2 className="font-editorial mt-5 text-3xl text-[var(--maroon-dark)]">Research team</h2></div><div className="grid gap-4 sm:grid-cols-2"><TeamPlaceholder label="Faculty lead" /><TeamPlaceholder label="Research assistant" /><TeamPlaceholder label="Ontology collaborators" /><TeamPlaceholder label="Data and methods contributors" /></div></div></section></div></>; }
function TeamPlaceholder({ label }: { label: string }) { return <div className="border border-dashed border-[var(--line)] p-5"><p className="text-xs font-semibold uppercase tracking-[.06em] text-[var(--muted)]">{label}</p><p className="mt-3 text-sm italic text-[var(--muted)]">Name and profile to be supplied</p></div>; }
