import { RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";

export interface ExplorerFilters { category: string; relevance: string; source: string; year: string; confidence: string }

export function FilterSidebar({ filters, categories, sources, years, onChange, onClear }: { filters: ExplorerFilters; categories: string[]; sources: string[]; years: string[]; onChange: (key: keyof ExplorerFilters, value: string) => void; onClear: () => void }) {
  const selectClass = "focus-ring h-11 w-full rounded-[4px] border border-[var(--line)] bg-white px-3 text-sm";
  return <aside className="border border-[var(--line)] bg-[var(--white)] p-5 lg:sticky lg:top-24 lg:self-start"><div className="flex items-center justify-between"><h2 className="font-semibold">Filter repository</h2><Button variant="ghost" size="icon" onClick={onClear} title="Clear all filters" aria-label="Clear all filters"><RotateCcw className="h-4 w-4" /></Button></div><div className="mt-5 grid gap-5"><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.06em] text-[var(--muted)]">Food category<select className={selectClass} value={filters.category} onChange={(event) => onChange("category", event.target.value)}><option value="all">All categories</option>{categories.map((value) => <option key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.06em] text-[var(--muted)]">Human review label<select className={selectClass} value={filters.relevance} onChange={(event) => onChange("relevance", event.target.value)}><option value="relevant">Relevant</option><option value="irrelevant">Irrelevant</option><option value="pending">Pending review</option><option value="all">All labels</option></select></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.06em] text-[var(--muted)]">Source<select className={selectClass} value={filters.source} onChange={(event) => onChange("source", event.target.value)}><option value="all">All sources</option>{sources.map((value) => <option key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.06em] text-[var(--muted)]">Publication year<select className={selectClass} value={filters.year} onChange={(event) => onChange("year", event.target.value)}><option value="all">All years</option>{years.map((value) => <option key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-[.06em] text-[var(--muted)]">Classifier confidence<select className={selectClass} value={filters.confidence} onChange={(event) => onChange("confidence", event.target.value)}><option value="all">Any or unavailable</option><option value="0.5">50% and above</option><option value="0.7">70% and above</option><option value="0.9">90% and above</option></select></label></div></aside>;
}
